import 'package:get/get.dart';

class Languages extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "lunch": "Lunch",
          "breakfast": "Breakfast",
          "dinner": "Dinner",
          "settings": "Settings",
          "Import Students Data": "Import Students Data",
          "import cafe users": "import cafe users",
          "Export Report": "Export Report",
          "export to get analysis": "export to get analysis",
          "Clear Todays Serving": "Clear Todays Serving",
          "clear todays serving history": "clear todays serving history",
          "Clear All Data": "Clear All Data",
          "Erase all the students data": "Erase all the students data",
          "Language": "Language",
          "Change Language": "Change Language",
          "Not Verified": "Not Verified",
          "Try Again": "Try Again",
          "The Student Doesn't Exist in the Cafe's Database":
              "The Student Doesn't Exist in the Cafe's Database",
          "Twice Entrance": "Twice Entrance",
          "Ok": "Ok",
          "The Student is Coming for the Second time.":
              "The Student is Coming for the Second time.",
          "Are you sure to clear?": "Are you sure to clear?",
          "No": "No",
          "Yes": "Yes",
          "MU Meals": "MU Meals",
          'Scan QR': 'Scan QR',
          "Served Students": "Served Students",
          "Students left": "Students left",
          "Total Students": "Total Students",
          "Import Pictures of Students": "Import Pictures of Students",
          "import pictures for better verification":
              "import pictures for better verification",
          "Verify breakfast": "Verify Breakfast",
          "Verify lunch": "Verify Lunch",
          "Verify dinner": "Verify Dinner"
        },
        'tg_ET': {
          "lunch": "ምሳሕ",
          "breakfast": "ቑርሲ",
          "dinner": "ድራር",
          "settings": "መፍትሒ",
          "Import Students Data": "ናይ ተምሃሮ ዳታ አእትው",
          "import cafe users": "ናይ ካፌ ተጠቀምቲ ዳታ አእትው",
          "Export Report": "ሪፖርት አውፅእ",
          "export to get analysis": "ሪፖርት ልምእካብ ዳታ የውፅኡ",
          "Clear Todays Serving": "ናይ ሎማዓንቲ ዳታ ደምስስ",
          "clear todays serving history": "ናይ ሎማዓንቲ መዝገብ ደምስስ",
          "Clear All Data": "ሙሉእ ናይ ተምሃሮ መዝገብ አጥፍእ",
          "Erase all the students data": "ኩሉ ናይ ተምሃሮ ዳታ አጥፍእ",
          "Language": "ቋንቋ",
          "Change Language": "ቋንቋ ቐይር",
          "Not Verified": "አይተረኸበን",
          "Try Again": "ኻልኣይ ሞክር",
          "The Student Doesn't Exist in the Cafe's Database":
              "ተምሃራይ ኣብ ዳታ አይተረኸበን",
          "Twice Entrance": "ንኻልኣይ ግዜ ይኣቲ ኣሎ",
          "Ok": "እሺ",
          "The Student is Coming for the Second time.":
              "ተምሃራይ ንኻልኣይ ግዜ ስካን አግቢሩ",
          "Are you sure to clear?": "ንምድምሳስ እርግፀኛ ድዮም?",
          "No": "ኣይ",
          "Yes": "እወ",
          "MU Meals": "መቐለ ዩኒቨርሲቲ",
          'Scan QR': 'QR አልዕል',
          "Served Students": "ዝተጠቐሙ ተምሃሮ",
          "Students left": "ዝቐረዩ ተምሃሮ",
          "Total Students": "ጠቕላላ ተምሃሮ",
          "Import Pictures of Students": "ናይ ተምሃሮ ፎቶታት አእትው",
          "import pictures for better verification": "ንዝበለፀ መረጋገፂ ፎቶ የእትዉ",
          "Verify breakfast": "ቑርሲ የረጋግፁ",
          "Verify lunch": "ምሳሕ የረጋግፁ",
          "Verify dinner": "ድራር የረጋግፁ"
        },
        'am_ET': {
          "lunch": "ምሳ",
          "breakfast": "ቁርስ",
          "dinner": "እራት",
          "settings": "መፍቻ",
          "Import Students Data": "የተማሪዎች ዳታ አስገባ",
          "import cafe users": "የካፌ ተጠቃሚዎች ዳታ አስገባ",
          "Export Report": "ሪፖርት አውጣ",
          "export to get analysis": "ሪፖርት ለማግኘት ዳታ ያስወጡ",
          "Clear Todays Serving": "የዛሬ ዳታ ደምስስ",
          "clear todays serving history": "የዛሬ መዝገብ ደምስስ",
          "Clear All Data": "ሙሉ የተማሪዎች መዝገብ አጥፋ",
          "Erase all the students data": "ሁሉም የተምሪዎች ዳታ አጥፋ",
          "Language": "ቋንቋ",
          "Change Language": "ቋንቋ ቀይር",
          "Not Verified": "አልተገኘም",
          "Try Again": "ድጋሚ ሞክር",
          "The Student Doesn't Exist in the Cafe's Database":
              "ተማሪ በዳታ ዝርዝር አልተገኘም",
          "Twice Entrance": "ለሁለተኛ ግዜ እየገባ ነው",
          "Ok": "እሺ",
          "The Student is Coming for the Second time.":
              "ተማሪው ለሁለተኛ ጊዜ ስካን አስደረገ",
          "Are you sure to clear?": "ለመደምሰስ እርግጠኛ ኖት?",
          "No": "አይ",
          "Yes": "አዎ",
          "MU Meals": "መቐለ ዩኒቨርሲቲ",
          'Scan QR': 'QR አንሳ',
          "Served Students": "የተጠቀሙ ተማሪዎች",
          "Students left": "የቀሩ ተማሪዎች",
          "Total Students": "ጠቅላላ ተማሪዎች",
          "Import Pictures of Students": "የተማሪዎች ፎቶ አስገባ",
          "import pictures for better verification": "ለበለጠ ማረጋገጫ ፎቶዎች ያስገቡ",
          "Verify breakfast": "ቁርስ ያረጋግጡ",
          "Verify lunch": "ምሳ ያረጋግጡ",
          "Verify dinner": "እራት ያረጋግጡ"
        },
      };
}
